version: "3" 
services: 
  web: 
    image: chaosjohn0827/friendlyhello:latest
    deploy: 
      replicas: 5
      resources: 
        limits: 
          cpus: "0.1"
          memory: 50M
      restart_policy: 
        condition: on-failure
    ports: 
      - "40080:80" 
    networks: 
      - webnet
  visualizer: 
    image: dockersamples/visualizer:stable
    ports: 
      - "48080:8080"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock" 
    deploy: 
      placement: 
        constraints: [node.role == manager] 
    networks: 
      - webnet
  redis: 
    image: redis 
    ports: 
      - "46379:6379"
    volumes: 
      - /docker/redis/data:/data
    deploy: 
      placement: 
        constraints: [node.role == manager] 
    networks: 
      - webnet
networks: 
  webnet:
